config/routes.rb
Rails.application.routes.draw do
  root "activities#index"
  mount Liveness::Status => '/status'
  mount GoodJob::Engine => 'good_job'

  resource :contributors, only: [:show]
  resources :activities, only: [:index,:show] do
    resources :papers
    resources :categories, only: [:index, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'my_proposals' => "users/index#show"
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    resources :activities do
      member do
        put :dup
      end
      resources :reviewers, only: [:index,:new,:create,:destroy]
      resources :papers, only: [:index, :show, :update] do
        resources :comments, only: [:create, :destroy]
      end
      resources :mails, only: [:create]
      resources :speakers, only: [:index]
      resource :stats, only: [:show]
    end
    resources :papers, only: [] do
      resources :reviews, only: [:create]
      post 'approve' => "reviews#approve"
      post 'disapprove' => "reviews#disapprove"
      post 'accept' => "reviews#accept"
      post 'reject' => "reviews#reject"
    end

    resources :tags, only: [:index]

    resources :users, only: [:index, :edit, :update] do
      resource :contributor, only: [:create, :destroy]

      get '/designate' => "users#designate"
      get '/undesignate' => "users#undesignate"
    end
  end
end

app/models/paper.rb
class Paper < ApplicationRecord
  include AASM
  ALL_STATUS = %w{submitted reviewed accepted rejected withdrawn}
  ALL_LANGUAGES = %w{Chinese English}
  StateClass = {
    "submitted" => 'label-info',
    "reviewed" => 'label-primary',
    "accepted" => 'label-success',
    "rejected" => 'label-warning',
    "withdraw" => 'label-danger'
  }

  attr_writer :custom_field_errors

	mount_uploader :speaker_avatar, PictureUploader
  mount_uploader :attachement, AttachementUploader

  %i[abstract speaker_bio title].each do |attr|
    define_method([attr, 'words'].join('_')) { send(attr).to_s.scan(/\w+/) }
  end

  validates :title_words, length: { in: Settings.paper.title.min..Settings.paper.title.max }
  validates :abstract_words, length: { in: Settings.paper.abstract.min..Settings.paper.abstract.max }
  validates :speaker_bio_words, length: { in: Settings.paper.bio.min..Settings.paper.bio.max }

	validates_presence_of :title
	validates_presence_of :abstract
	validates_presence_of :outline
  validate :validate_custom_fields
  validate :validate_proposal_expires, on: :create
  validates_presence_of :speaker_bio, :language

  # enum state: Hash[ALL_STATUS.map{|x| [x,x]}]
  enum language: Hash[ALL_LANGUAGES.map{|x| [x,x]}]

	belongs_to :activity, counter_cache: true
	belongs_to :user

  has_many :reviews
  has_many :comments

  acts_as_taggable_on :tags

  delegate :github_url, to: :user, prefix: true
  delegate :name, to: :activity, prefix: true
  delegate :name, to: :user, prefix: :speaker

  scope :state, -> (state) { where(state: state) }
  scope :opened, -> { where.not(state: :withdrawn)}

  aasm(column: :state) do
    state :submitted , initial: true
    state *(ALL_STATUS[1..-1].map(&:to_sym))
    event :view do
      transitions from: :submitted , to: :reviewed
    end
    event :accept do
      transitions from: :reviewed, to: :accepted
    end
    event :reject do
      transitions from: :reviewed, to: :rejected
    end
    event :withdraw do
      transitions to: :withdrawn
    end
  end

  #def self.states
  #  aasm.states.map(&:name)
  #end

  after_create :notify_user

  default_value_for :speaker_name do |paper|
    paper.user.try(:name)
  end

  default_value_for :uuid do
    SecureRandom.hex(4)
  end

  def to_param
    uuid
  end

  def custom_fields
    activity.custom_fields.map do |field|
      {
        name: field.name,
        value: answer_of_custom_fields[field.id.to_s] || nil
      }
    end
  end

  def custom_field_errors
    @custom_field_errors ||= {}
  end

  def reviewed_by?(user)
    reviews.pluck(:user_id).include?(user.id)
  end

  # NOTICE: to_yaml will be override
  def self.as_yaml(options = {})
    result = all.map { |item| item.as_json(options) }
    result = {"#{model_name.plural}" => result} if options[:include_root]
    result.to_yaml
  end

  def as_json(options = {})
    hostname = options[:hostname]
    result_hash = {
      bio: self.class.markdown(speaker_bio),
      subject: title,
      summary: self.class.markdown(abstract),
      language: language,
    }
    result_hash.stringify_keys!
    # remove unused whilyye space characters, and tailing new lines
    result_hash.each do |key, value|
      result_hash[key] = value.gsub(/(\s*)\n(\s*)/,"\n").gsub(/[\n\r]*\z/,"") if value
    end
    # merge with speaker
    speaker_hash = user.as_json(options)
    speaker_hash.merge(result_hash)
  end

  def total_approve
    reviews.where(reviewed: "approve").count
  end

  def total_disapprove
    reviews.where(reviewed: "disapprove").count
  end

  private

  def notify_user
    PapersMailer.notification_after_create(self.id).deliver_now!
  end

  def validate_custom_fields
    return if activity.nil?
    self.activity.custom_fields.each do |cf|
      val = self.answer_of_custom_fields[cf.id.to_s]
      if cf.required && val.blank?
        custom_field_errors[cf.id.to_s] = I18n.translate("errors.messages.blank")
        self.errors.add :custom_field_errors, I18n.translate("errors.messages.blank")
      end
    end
  end

  def validate_proposal_expires
    return if activity.nil?
    unless activity.open?
      errors[:base] << I18n.translate("flash.cfp_not_open_yet")
    end
  end

end

app/controllers/admin/papers_controller.rb
class Admin::PapersController < Admin::ApplicationController
  include ApplicationHelper
  before_action :set_activity
  before_action :set_paper, only: [:show, :update]

  add_sortable_column "users.name"

  def index
    @papers = apply_search_filter(Paper.preload(:user, :activity, :comments, :reviews).joins(:user).where(activity: @activity).order("#{sort_column} #{sort_direction}"))
    @notification = Notification.new

    respond_to do |format|
      # TODO: Filter necessary columns
      format.yml do
        send_data PapersJSONExporter.new(@papers).perform.to_yaml,
                  type: "application/yml",
                  disposition: "attachment; filename=papers.yml"
      end
      format.xlsx do
        send_file PapersXLSXExporter.new(@papers).perform
      end
      format.html
    end
  end

  def show
    @custom_fields = @activity.custom_fields
    @new_comment = Comment.new
  end

  def update
    @paper.update(paper_params)
    respond_to do |format|
      format.html { redirect_to admin_activity_paper_path(@activity, @paper) }
      format.json {
        html = render_to_string(partial: "display_tags", formats: [:html], locals: {tags: @paper.tags})
        render json: {paper: @paper, tags: @paper.tags.collect{|t| t.name}, display_tags_html: html}
      }
    end
  end
  private

  def set_activity
    @activity = Activity.preload(:custom_fields).find_by(permalink: params[:activity_id])
  end

  def set_paper
    @paper = @activity.papers.find_by(uuid: params[:id])
  end

  def paper_params
    params.require(:paper).permit(:tag_list)
  end

  def apply_search_filter(query)
    if params[:commit] == "Search"
      # search by tag
      if params[:search_field] == "tag"
        wild = params[:search_type] != "equal"
        final_q = query
        params[:search_key].split(",").each do |tag|
          final_q = final_q.tagged_with(tag, any: true, wild: wild)
        end
        final_q
      else # search by column
        if fixed_search_fields.include? params[:search_field]
          column = "lower(#{params[:search_field]})" # search_field should be safe
        elsif get_all_custom_field_strings.include? params[:search_field]
          # find the custom field by name
          custom_field = @activity.custom_fields.find_by!(name: params[:search_field])
          # combine sql
          column = "lower(answer_of_custom_fields->>'#{custom_field.id}')"
        else
          raise "Invalid search field"
        end
        if params[:search_type] == "equal"
          query.where("#{column} = lower(?)", params[:search_key])
        else
          query.where("#{column} like lower(?)", "%#{params[:search_key]}%")
        end
      end
    else
      params[:search_field] = ''
      params[:search_key] = ''
      query
    end
  rescue
    query
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :check_activity_valid_for_submit?, only: [:new, :create]
  before_action :current_activity, if: lambda{params.has_key?(:activity_id)}
  before_action :authenticate_user!
  # before_action :require_current_user, only: [:show,:edit]
  load_and_authorize_resource find_by: :uuid

  # GET /papers
  # GET /papers.json
  def index
    @papers = @activity.papers.where(user_id: current_user.id)
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @user = @paper.user
    @invited_user = User.find_by_email(@paper.inviting_email)
    @custom_fields = @activity.custom_fields
  end

  # GET /papers/new
  def new
    @paper = current_user.papers.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = @activity.papers.new(paper_params)
    @paper.user = current_user
    logger.info @paper.inspect
    respond_to do |format|
      if @paper.save
        @activity.notify("new_paper", @paper)
        format.html { redirect_to activity_paper_path(@activity, @paper), notice: 'Paper was successfully created.' }
      else
        format.html {
          render :new}
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to activity_paper_path(@activity, @paper), notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.withdraw!
    @paper.activity.notify("paper_status_changed", @paper)
    respond_to do |format|
      format.html { redirect_to activity_paper_path(@activity, @paper), notice: 'Paper was successfully withdrawn.' }
      format.json { head :no_content }
    end
  end

  private

  def check_activity_valid_for_submit?
    unless current_activity.open?
      flash[:warning] = t('flash.cfp_not_open_yet')
      redirect_to current_activity
      false
    end
  end

  def current_activity
    @activity ||= Activity.find_by(permalink: params[:activity_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def paper_params
    paper_params = params.require(:paper).permit(:language, :pitch, :speaker_bio, :title, :abstract, :outline, :file_name, :status, :activity_id,:inviting_email, :attachement, :remove_attachement, answer_of_custom_fields: current_activity.custom_fields.map{|x| x.id.to_s} )
    paper_params.permit!

  end
end

app/helpers/admin/papers_helper.rb
module Admin::PapersHelper
  def admin_approve_button(paper, user)
    review = Review.find_by(paper: paper, user: user)
    return if review
    link_to "Approve", admin_paper_approve_path(paper), method: "POST", class: "btn btn-success"
  end

  def admin_disapprove_button(paper, user)
    review = Review.find_by(paper: paper, user: user)
    return if review
    link_to "Disapprove", admin_paper_disapprove_path(paper), method: "POST", class: "btn btn-danger"
  end

  def admin_accept_button(paper)
    return if !paper.may_accept?
      link_to "Accept", admin_paper_accept_path(paper), method: "POST", class: "btn btn-success"
  end

  def admin_reject_button(paper)
    return if !paper.may_reject?
      link_to "Reject", admin_paper_reject_path(paper), method: "POST", class: "btn btn-danger"
  end
end

app/helpers/papers_helper.rb
module PapersHelper
  def build_custom_field_input(form_builder, custom_field, base_attr = :answer_of_custom_fields)
    base_obj = form_builder.object
    prefix = form_builder.object_name
    value_field_name = "#{prefix}[#{base_attr}][#{custom_field.id}]"
    value = base_obj.send(base_attr).send(:"[]", custom_field.id.to_s)
    case custom_field.field_type
    when 'text'
      text_area_tag value_field_name, value, class: "form-control"
    when 'checkboxes'
      render partial: "checkboxes", locals: {custom_field: custom_field, value_field_name: value_field_name, value: value}
    when 'radios'
      render partial: "radios", locals: {custom_field: custom_field, value_field_name: value_field_name, value: value}
    when 'selects'
      render partial: "selects", locals: {custom_field: custom_field, value_field_name: value_field_name, value: value}  
    else #text
      text_field_tag value_field_name, value, class: "form-control"
    end

  end

  def paper_state_badge(paper)
    style = "label label-info"
    case paper.state
    when "accepted"
      style = "label label-success"
    when "rejected"
      style = "label label-danger"
    when "withdrawn"
      style = "label label-warning"
    end
    content_tag :span, paper.state, class: style
  end

  def withdraw_proposal_button(activity, paper, custom_options = {})
    return if paper.withdrawn?

    options = {method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning"}
    options.merge!(custom_options)

    link_to activity_paper_path(activity, paper), options  do
      concat content_tag(:span, nil, class: "fa fa-exclamation-circle")
      concat " Withdraw Proposal"
    end
  end
end

app/views/admin/papers/_comment.html.slim
div class="comment-#{comment.id}" id="comment-#{comment.id}"
  h4 #{comment.user.name} says:
  .well
    p == markdown(comment.text)
  p.text-right
    = "created at #{comment.created_at} "
    - if comment.user == current_user
      = link_to "delete", admin_activity_paper_comment_path(@activity, @paper, comment), method: "DELETE"
hr

app/views/admin/papers/_display_tags.html.slim
- tags.each do |tag|
  = " "
  .label.label-primary.tag
    = tag.name
= " "

app/views/admin/papers/_tag_field.html.slim
.add-tag-field.well
  = simple_form_for paper, url: admin_activity_paper_path(@activity, paper), method: "PATCH", remote: true, data: { type: :json } do |f|
    = f.input :tag_list, input_html: {value: paper.tag_list.join(', ')}
    = f.submit "Save", class: "btn btn-primary"
    = link_to "Close", "#", class: "btn btn-default remove-tag-field", data:{ id: paper.id}
  = "<script>$(document).ready(function(){window.CreateTagsInput('.paper_tag_list > input','#{admin_tags_path}');});</script>".html_safe

app/views/admin/papers/index.html.slim
.col-md-12
  .page-header
    h1
      = "Papers of " + @activity.name
  div.search_bar
    = form_tag admin_activity_papers_path(@activity), method: :get
      span.search_field
        = " Search by:"
        = select_tag "search_field", options_for_select(fixed_search_fields + get_all_custom_field_strings, params[:search_field]), include_blank: true
      span.search_type
        = " Search type:"
        = select_tag "search_type", options_for_select(["like","equal"], params[:search_type])
      span.search_key
        = " Keyword:"
        span.tag-input
          = text_field_tag "", params[:search_key], class: "input-field"
        span.normal-input
          = text_field_tag "", params[:search_key], class: "input-field"
      span.search_submit
        = " | "
        = submit_tag("Search", class: "btn btn-primary")
        = " | "
        = submit_tag("Clear Search", class: "btn btn-info")
        = " | "
        = link_to "Stats", admin_activity_stats_path(@activity), class: "btn btn-success"
    = "<script>$(document).ready(function(){window.CreateTagsInput('.search_bar .search_key .tag-input .input-field','#{admin_tags_path}');});</script>".html_safe
  = form_for @notification, url: admin_activity_mails_path(@activity) do |f|
    p
      = "Total: #{@papers.size} papers"
    table.table.tble-striped.papers
      thead
        tr
          th
            = check_box_tag "notification_check_all", nil, false, id: "notification_check_all"
          th
            | #
            = sortable("id")
          th
            | Title
            = sortable("title")
          th Tags
          th
            | Comment counts
          th
            | State
            = sortable("state")
          th
            | User
            = sortable("users.name")
          th
            | Approve/Disapprove
          th
            | Github
            = sortable("users.github_username")
          - @activity.custom_fields.each do |field|
            th class="cf-#{field.id}"
              = field.name
          th
      tbody
        - @papers.each do |paper|
          tr id=("paper_#{paper.id}")
            td
              div.checkbox
                label
                  = check_box_tag "notification[ids][]", paper.id, false, id: "notification_ids_#{paper.id}"
            td
              = paper.id
            td
              = paper.title
            td
              - paper.tags.each do |tag|
                a.label.label-primary.paper-tag data-tag-name="#{tag.name}"
                  =tag.name
                |&nbsp;
            td
              = paper.comments.count
            td
              a.label.paper-state data-state="#{paper.state}" class="#{Paper::StateClass[paper.state]}"
                = paper.state
            td
              = paper.user.name
            td
              | approve: 
              span.approve-vote-count #{paper.total_approve}
              br
              | disapprove:
              span.disapprove-vote-count #{paper.total_disapprove}
            td
              = link_to paper.user.github_link_text, "https://github.com/#{paper.user.github_username}"
            - @activity.custom_fields.each do |field|
              td = paper.answer_of_custom_fields[field.id.to_s]
            td
              .btn-group
                = link_to "show", admin_activity_paper_path(@activity,paper), class: "btn btn-primary"
                = admin_approve_button(paper, current_user)
                = admin_disapprove_button(paper, current_user)
                = admin_accept_button(paper)
                = admin_reject_button(paper)
              = " "

    = link_to "Back", admin_activity_path(@activity), class: "btn btn-default"

    div.notification
      hr
      h3 Notice Mail
      p
        = f.text_field :subject, class: "form-control"
      p
        = f.text_area :content, rows: 12, class: "form-control"
      p
        = f.submit "Send", class: "btn btn-default"

app/views/admin/papers/show.html.slim
.col-md-12
  .page-header
    h1
      = @paper.title
  table.table
    tbody
      tr
        th tags
        td
          span.display_tags
            = render(partial: "display_tags", locals: {tags: @paper.tags})
          a.edit-tag-button.btn.btn-default(data-id="#{@paper.id}") Edit tag
          .field-container.hide(data-id="#{@paper.id}")
            = render(partial: "tag_field", locals: {paper: @paper})

      tr
        th Language
        td = @paper.language
      tr
        th Subject
        td
          = @paper.title
      tr
        th Abstract
        td
          == markdown(@paper.abstract)
      tr
        th Outline
        td
          == markdown(@paper.outline)
      tr
        th Pitch
        td
          == markdown(@paper.pitch)
      - if @paper.custom_fields.size > 0
        tr
          th Other Fields
          td
            - @paper.custom_fields.each do |field|
              h4 = field[:name]
              p = field[:value]
      tr
        th Speaker Avatar
        td
          = image_tag @paper.user.photo.url, class: "avatar"
      tr
        th Speaker Bio
        td = @paper.speaker_bio
      tr
        th Status
        td
          = @paper.state
      tr
        th User
        td
          = @paper.user.name
      tr
        th Attachement
        td
          - if @paper.attachement.present?
            = link_to @paper.attachement.identifier, @paper.attachement.url
  .btn-group
    = admin_approve_button(@paper, current_user)
    = admin_disapprove_button(@paper, current_user)
    = admin_accept_button(@paper)
    = admin_reject_button(@paper)
    = link_to "Back", admin_activity_papers_path(@activity), class: "btn btn-default"

h2 comments
div#comment-group
  - @paper.comments.each do |comment|
    = render partial: "comment", locals: { comment: comment }

h3 add comments
p#comment_error
= simple_form_for @new_comment, url: admin_activity_paper_comments_path(@activity, @paper), method: "POST", remote: true do |f|
  = f.input :text, label: false
  = f.submit "Submit", class: "btn btn-primary"