config/routes.rb
Rails.application.routes.draw do
  root "activities#index"
  mount Liveness::Status => '/status'
  mount GoodJob::Engine => 'good_job'

  resource :contributors, only: [:show]
  resources :activities, only: [:index,:show] do
    resources :papers
    resources :categories, only: [:index, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'my_proposals' => "users/index#show"
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    resources :activities do
      member do
        put :dup
      end
      resources :reviewers, only: [:index,:new,:create,:destroy]
      resources :papers, only: [:index, :show, :update] do
        resources :comments, only: [:create, :destroy]
      end
      resources :mails, only: [:create]
      resources :speakers, only: [:index]
      resource :stats, only: [:show]
    end
    resources :papers, only: [] do
      resources :reviews, only: [:create]
      post 'approve' => "reviews#approve"
      post 'disapprove' => "reviews#disapprove"
      post 'accept' => "reviews#accept"
      post 'reject' => "reviews#reject"
    end

    resources :tags, only: [:index]

    resources :users, only: [:index, :edit, :update] do
      resource :contributor, only: [:create, :destroy]

      get '/designate' => "users#designate"
      get '/undesignate' => "users#undesignate"
    end
  end
end

app/controllers/admin/reviewers_controller.rb
class Admin::ReviewersController < ApplicationController
  before_action :set_activity, :set_relationships
  authorize_resource :user_activity_relationship

  def index
    @reviewers = []
    @relationships.each do |relationship|
      @reviewers << User.find(relationship.user_id)
    end
  end

  def new
    @relationship = UserActivityRelationship.new
    @users = User.all
  end

  def create
    @relationship = UserActivityRelationship.new(relationship_params)
    @relationship.activity_id = @activity.id
    if @relationship.save
      flash[:notice] = "Add new reviewer successfully!"
      redirect_to admin_activity_reviewers_path
    else
      render :new
    end
  end

  def destroy
    @relationship = UserActivityRelationship.where(activity_id: params[:activity_id], user_id: params[:id])
    @relationship.each do |relationship|
      relationship.destroy
    end
    redirect_to admin_activity_reviewers_path
  end
  private

  def set_activity
    @activity = Activity.find_by(permalink: params[:activity_id])
  end
  def set_relationships
    @relationships = UserActivityRelationship.where(activity_id: @activity.id)
  end
  def relationship_params
    params.require(:user_activity_relationship).permit(:user_id)
  end
end

app/helpers/admin/reviewers_helper.rb
module Admin::ReviewersHelper
end

app/views/admin/reviewers/index.html.erb
<h1 class="text-center">Reviewers</h1>
<div class="col-md-8 col-md-offset-1">
<table class="table">
<thead>
  <tr>
    <th>#</th>
    <th>name</th>
    <th>firstname</th>
    <th>lastname</th>
    <th>photo</th>
    <th>managment</th>
  </tr>
</thead>
<tbody>
  <% @reviewers.each do |reviewer| %>
  <tr> 
    <td><%= reviewer.id %></td>
    <td><%= reviewer.name %></td>
    <td><%= reviewer.firstname %></td>
    <td><%= reviewer.lastname %></td>
    <td><%= image_tag(reviewer.photo.url, width: 100, height: 100) if reviewer.photo.present? %></td>
    <td>
      <%= link_to 'delete', admin_activity_reviewer_path(@activity,reviewer), method: :delete %> 
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

<div class="col-md-3">
  <%= link_to 'add reviewers', new_admin_activity_reviewer_path(@activity), class: "btn btn-default" %>
</div>

app/views/admin/reviewers/new.html.erb
<%= simple_form_for @relationship, url: admin_activity_reviewers_path do |f| %>
    <%= f.input :user_id, collection: @users%>
    <%= f.submit%>
<% end %>