config/routes.rb
Rails.application.routes.draw do
  root "activities#index"
  mount Liveness::Status => '/status'
  mount GoodJob::Engine => 'good_job'

  resource :contributors, only: [:show]
  resources :activities, only: [:index,:show] do
    resources :papers
    resources :categories, only: [:index, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'my_proposals' => "users/index#show"
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    resources :activities do
      member do
        put :dup
      end
      resources :reviewers, only: [:index,:new,:create,:destroy]
      resources :papers, only: [:index, :show, :update] do
        resources :comments, only: [:create, :destroy]
      end
      resources :mails, only: [:create]
      resources :speakers, only: [:index]
      resource :stats, only: [:show]
    end
    resources :papers, only: [] do
      resources :reviews, only: [:create]
      post 'approve' => "reviews#approve"
      post 'disapprove' => "reviews#disapprove"
      post 'accept' => "reviews#accept"
      post 'reject' => "reviews#reject"
    end

    resources :tags, only: [:index]

    resources :users, only: [:index, :edit, :update] do
      resource :contributor, only: [:create, :destroy]

      get '/designate' => "users#designate"
      get '/undesignate' => "users#undesignate"
    end
  end
end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="footer-links">
      <li><%= link_to "Ruby Conf Taiwan", "https://rubyconf.tw" %></li>
      <li><%= link_to "Twitter", "https://twitter.com/rubyconftw" %></li>
      <li><%= link_to "Contributors", contributors_path %></li>
    </ul>
    <p>
    Contributed by <%= link_to "5xRuby CO., LTD", "https://5xruby.com" %>.
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RubyConfTW CFP", root_path, class: "navbar-brand", :"data-no-turbolink" => true %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? && current_user.is_admin %>
          <li><%= link_to 'Activities', admin_activities_path%></li>
          <li><%= link_to 'Users', admin_users_path %></li>
          <%= admin_review_paper_link(Activity.recent.first)  %>
        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">


        <% if user_signed_in? %>
          <li><%= link_to "My Proposals", my_proposals_path %></li>
        <% end %>

        <li><%= link_to "Events", root_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag(current_user.photo.url, width: 20, height: 20, class: "img-circle") if current_user.photo.present? %>
              <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path do %>
                  <span class="fa fa-user"></span>  Profile
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="fa fa-sign-out"></span> Sign out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>